"""empty message

Revision ID: 67d8161f204a
Revises: 
Create Date: 2025-07-07 18:48:54.296552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d8161f204a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('desired_exam_date', sa.Date(), nullable=True),
    sa.Column('rock_routes', sa.Boolean(), nullable=True),
    sa.Column('snow_routes', sa.Boolean(), nullable=True),
    sa.Column('ice_routes', sa.Boolean(), nullable=True),
    sa.Column('mixed_routes', sa.Boolean(), nullable=True),
    sa.Column('high_altitude_routes', sa.Boolean(), nullable=True),
    sa.Column('ski_routes', sa.Boolean(), nullable=True),
    sa.Column('difficulty_category', sa.String(), nullable=True),
    sa.Column('passport_type', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('passport_issued_by', sa.String(), nullable=True),
    sa.Column('passport_unit_code', sa.String(), nullable=True),
    sa.Column('passport_issue_date', sa.Date(), nullable=True),
    sa.Column('passport_scan_main', sa.String(), nullable=True),
    sa.Column('passport_scan_registration', sa.String(), nullable=True),
    sa.Column('other_id_document_name', sa.String(), nullable=True),
    sa.Column('other_id_document_scan', sa.String(), nullable=True),
    sa.Column('postal_index', sa.String(), nullable=True),
    sa.Column('registration_address', sa.String(), nullable=True),
    sa.Column('actual_address', sa.String(), nullable=True),
    sa.Column('snils', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_instructors_id'), 'instructors', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('change_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_history_id'), 'change_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_history_id'), table_name='change_history')
    op.drop_table('change_history')
    op.drop_table('users')
    op.drop_index(op.f('ix_instructors_id'), table_name='instructors')
    op.drop_table('instructors')
    # ### end Alembic commands ###
